services:
  motion:
    build:
      context: .
      dockerfile: motion/Dockerfile
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', 5557)); s.close()"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 15s
    restart: unless-stopped

  detection_coco:
    build:
      context: .
      dockerfile: detection_coco/Dockerfile
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # depends_on:
      # motion:
        # condition: service_healthy
    restart: unless-stopped

  detection_fire:
    build:
      context: .
      dockerfile: detection_fire/Dockerfile
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # depends_on:
      # motion:
        # condition: service_healthy
    restart: unless-stopped

  alert:
    build:
      context: .
      dockerfile: alert/Dockerfile
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    restart: unless-stopped


  system_monitor:
    build:
      context: .
      dockerfile: system_monitor/Dockerfile
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # depends_on:
      # motion:
        # condition: service_healthy
    restart: unless-stopped
    

networks:
  eyes_edge_net:
    driver: bridge

volumes:
  shared_data:
