services:
  motion:
    image: ${DOCKERHUB_USERNAME}/ds-motion:latest
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # healthcheck:
    #   test: ["CMD", "python", "-c", "import socket; s=socket.socket(); s.settimeout(2); s.connect(('127.0.0.1', 5557)); s.close()"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 5
    #   start_period: 15s
    deploy:
      labels:
        - com.ds.stack=ds_2026
        - com.ds.service=motion
      restart_policy:
        condition: any

  detection_coco:
    image: ${DOCKERHUB_USERNAME}/ds-detection-coco:latest
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # depends_on:
      # motion:
        # condition: service_healthy
    deploy:
      labels:
        - com.ds.stack=ds_2026
        - com.ds.service=detection_coco
      restart_policy:
        condition: any

  detection_fire:
    image: ${DOCKERHUB_USERNAME}/ds-detection-fire:latest
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # depends_on:
      # motion:
        # condition: service_healthy
    deploy:
      labels:
        - com.ds.stack=ds_2026
        - com.ds.service=detection_fire
      restart_policy:
        condition: any

  alert:
    image: ${DOCKERHUB_USERNAME}/ds-alert:latest
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    deploy:
      labels:
        - com.ds.stack=ds_2026
        - com.ds.service=alert
      restart_policy:
        condition: any


  system_monitor:
    image: ${DOCKERHUB_USERNAME}/ds-system-monitor:latest
    volumes:
      - shared_data:/app/shared
      - ./logs:/app/logs
      - /etc/hostname:/host_hostname:ro
    networks:
      - eyes_edge_net
    # depends_on:
      # motion:
        # condition: service_healthy
    deploy:
      labels:
        - com.ds.stack=ds_2026
        - com.ds.service=system_monitor
      restart_policy:
        condition: any
    

networks:
  eyes_edge_net:
    driver: overlay
    attachable: true

volumes:
  shared_data:
